# Generated by Django 2.2 on 2019-04-30 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_profile', '0002_auto_20190428_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_profile.User'),
        ),
    ]
