# Generated by Django 2.2 on 2019-05-01 13:43

from django.db import migrations, models
import upload_profile.storage


class Migration(migrations.Migration):

    dependencies = [
        ('upload_profile', '0004_auto_20190501_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(storage=upload_profile.storage.ImageStorage(), upload_to='img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
